CREATE TABLE COUNTRY(
	COUNTRY_ID INT IDENTITY(0, 1) PRIMARY KEY,
	COUNTRY VARCHAR(20) NOT NULL
)

INSERT INTO COUNTRY
SELECT DISTINCT UPPER(TRIM(COUNTRY)) AS COUNTRY
FROM STAGING_TABLE
ORDER BY COUNTRY