CREATE TABLE CUSTOMER(
	CUSTOMER_ID_INT INT IDENTITY(0, 1) PRIMARY KEY,
	CUSTOMER_ID VARCHAR(50) NOT NULL,
	FIRST_NAME VARCHAR(20) NOT NULL,
	LAST_NAME VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(30) NOT NULL,
	PHONE_NUMBER VARCHAR(20),
	STREET VARCHAR(30) NOT NULL,
	CITY_ID INT NOT NULL FOREIGN KEY REFERENCES CITY(CITY_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	MEMBER BIT NOT NULL
)

INSERT INTO CUSTOMER
SELECT DISTINCT
	CUSTOMER_ID,
	UPPER(TRIM(SUBSTRING(CUSTOMER_NAME, 1, CHARINDEX(' ', CUSTOMER_NAME) - 1))) AS FIRST_NAME,
    UPPER(TRIM(SUBSTRING(CUSTOMER_NAME, CHARINDEX(' ', CUSTOMER_NAME) + 1, LEN(CUSTOMER_NAME) - CHARINDEX(' ', CUSTOMER_NAME)))) AS LAST_NAME,
	UPPER(TRIM(CONCAT(LEFT(TRIM(SUBSTRING(CUSTOMER_NAME, 1, CHARINDEX(' ', CUSTOMER_NAME) - 1)), 1), '.', TRIM(SUBSTRING(CUSTOMER_NAME, CHARINDEX(' ', CUSTOMER_NAME) + 1, LEN(CUSTOMER_NAME) - CHARINDEX(' ', CUSTOMER_NAME))), '@GMAIL.COM'))) AS EMAIL,
	UPPER(TRIM(PHONE_NUMBER)) AS PHONE_NUMBER,
	UPPER(TRIM(ADDRESS)) AS STREET,
	CITY_ID,
	CASE
		WHEN UPPER(LOYALTY_CARD) = 'YES' THEN 1
		ELSE 0
	END AS LOYALTY_CARD
FROM STAGING_TABLE A
INNER JOIN CITY B ON A.POSTAL_CODE = B.ZIP_CODE
ORDER BY LAST_NAME, FIRST_NAME