DROP TABLE STAGING_TABLE
ALTER TABLE CUSTOMER DROP COLUMN CUSTOMER_ID
ALTER TABLE "ORDER" DROP COLUMN ORDER_ID
ALTER TABLE PRODUCT DROP COLUMN PRODUCT_ID
EXEC SP_RENAME "CUSTOMER.CUSTOMER_ID_INT", "CUSTOMER_ID", "COLUMN"
EXEC SP_RENAME "ORDER.ORDER_ID_INT", "ORDER_ID", "COLUMN"
EXEC SP_RENAME "PRODUCT.PRODUCT_ID_INT", "PRODUCT_ID", "COLUMN"
CREATE UNIQUE NONCLUSTERED INDEX UNIQUE_IDX_COUNTRY ON COUNTRY(COUNTRY);
CREATE NONCLUSTERED INDEX IDX_COUNTRY_ID ON CITY(COUNTRY_ID)
CREATE UNIQUE NONCLUSTERED INDEX UNIQUE_IDX_EMAIL ON CUSTOMER(EMAIL) WHERE EMAIL IS NOT NULL;
CREATE NONCLUSTERED INDEX IDX_ORDER_DATE_ID ON "ORDER"(ORDER_DATE_ID)
CREATE NONCLUSTERED INDEX IDX_CUSTOMER_ID ON "ORDER"(CUSTOMER_ID)
CREATE UNIQUE NONCLUSTERED INDEX UNIQUE_IDX_ORDER_DATE ON ORDER_DATE(ORDER_DATE);
CREATE NONCLUSTERED INDEX IDX_ORDER_ID ON ORDER_LINE(ORDER_ID)
CREATE NONCLUSTERED INDEX IDX_PRODUCT_ID ON ORDER_LINE(PRODUCT_ID)
CREATE NONCLUSTERED INDEX IDX_COFFEE_TYPE_ID ON PRODUCT(COFFEE_TYPE_ID)
CREATE NONCLUSTERED INDEX IDX_ROAST_TYPE_ID ON PRODUCT(ROAST_TYPE_ID)
CREATE UNIQUE NONCLUSTERED INDEX UNIQUE_IDX_COFFEE_TYPE ON COFFEE_TYPE(COFFEE_TYPE);
CREATE UNIQUE NONCLUSTERED INDEX UNIQUE_IDX_ROAST_TYPE ON ROAST_TYPE(ROAST_TYPE);