CREATE TABLE CITY(
	CITY_ID INT IDENTITY(0, 1) PRIMARY KEY,
	COUNTRY_ID INT NOT NULL FOREIGN KEY REFERENCES COUNTRY(COUNTRY_ID) ON DELETE CASCADE,
	CITY VARCHAR(30) NOT NULL
)

INSERT INTO CITY
SELECT DISTINCT
	COUNTRY_ID,
	UPPER(TRIM(CITY)) AS CITY
FROM COUNTRY A
INNER JOIN STAGING_TABLE B ON A.COUNTRY = B.COUNTRY
ORDER BY COUNTRY_ID, CITY