CREATE TABLE POSTAL_CODE(
	POSTAL_CODE_ID INT IDENTITY(0,1) PRIMARY KEY,
	CITY_ID INT NOT NULL FOREIGN KEY REFERENCES CITY(CITY_ID) ON DELETE CASCADE,
	POSTAL_CODE VARCHAR(10)
)

INSERT INTO POSTAL_CODE
SELECT DISTINCT
	CITY_ID,
	UPPER(TRIM(POSTAL_CODE)) AS POSTAL_CODE
FROM STAGING_TABLE A
INNER JOIN CITY B ON A.CITY = B.CITY
ORDER BY CITY_ID, POSTAL_CODE