CREATE TABLE CUSTOMER(
	CUSTOMER_ID_INT INT IDENTITY(0, 1) PRIMARY KEY,
	CUSTOMER_ID VARCHAR(50) NOT NULL,
	FIRST_NAME VARCHAR(20) NOT NULL,
	LAST_NAME VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(50),
	PHONE_NUMBER VARCHAR(20),
	STREET VARCHAR(30) NOT NULL,
	POSTAL_CODE_ID INT NOT NULL FOREIGN KEY REFERENCES POSTAL_CODE(POSTAL_CODE_ID) ON DELETE CASCADE,
	LOYALTY_CARD BIT NOT NULL
)

INSERT INTO CUSTOMER
SELECT DISTINCT
	CUSTOMER_ID,
	UPPER(TRIM(SUBSTRING(CUSTOMER_NAME, 1, CHARINDEX(' ', CUSTOMER_NAME) - 1))) AS FIRST_NAME,
    UPPER(TRIM(SUBSTRING(CUSTOMER_NAME, CHARINDEX(' ', CUSTOMER_NAME) + 1, LEN(CUSTOMER_NAME) - CHARINDEX(' ', CUSTOMER_NAME)))) AS LAST_NAME,
	UPPER(TRIM(EMAIL)) AS EMAIL,
	UPPER(TRIM(PHONE_NUMBER)) AS PHONE_NUMBER,
	UPPER(TRIM(ADDRESS)) AS STREET,
	POSTAL_CODE_ID,
	CASE
		WHEN UPPER(LOYALTY_CARD) = 'YES' THEN 1
		ELSE 0
	END AS LOYALTY_CARD
FROM STAGING_TABLE A
INNER JOIN POSTAL_CODE B ON A.POSTAL_CODE = B.POSTAL_CODE
ORDER BY LAST_NAME, FIRST_NAME